
// tmc5160_regs_exhaustive.hpp
// Exhaustive register & field map for TMC5160/TMC5160A (Rev. 1.17, 2022-05-25).
// Approach: first-class fields (mask+shift). No C bitfields. Portable layout.
// Write access over SPI: add 0x80 to the register address.
// MIT-0.
//
// NOTE: The MSLUTx tables (0x60..0x67) and data-like registers are exposed as full 32-bit values;
//       these are inherently "raw" by design in the datasheet (pattern tables).
//
// Generated by ChatGPT.

#pragma once
#include <cstdint>

namespace tmc5160 {

// ---------- Core helpers ----------
struct Field {
    uint32_t mask;
    uint8_t  shift;
    constexpr uint32_t get(uint32_t v) const noexcept { return (v & mask) >> shift; }
    constexpr uint32_t set(uint32_t v, uint32_t x) const noexcept {
        v &= ~mask;
        v |= ((x << shift) & mask);
        return v;
    }
};

template<uint8_t LSB, uint8_t MSB>
constexpr Field F() {
    static_assert(MSB < 32 && LSB <= MSB, "bad bit range");
    constexpr uint32_t width = (uint32_t)MSB - (uint32_t)LSB + 1u;
    constexpr uint32_t mask  = (width == 32u ? 0xFFFFFFFFu : ((1u << width) - 1u)) << LSB;
    return Field{mask, LSB};
}

// Optional: sign-extend helper for reads
constexpr int32_t sign_extend(uint32_t value, uint8_t width) {
    return (int32_t)((value & ((1u << width) - 1u)) ^ (1u << (width - 1u))) - (int32_t)(1u << (width - 1u));
}

// ---------- Register addresses ----------
enum class Reg : uint8_t {
    // General configuration (0x00..0x0F)
    GCONF        = 0x00,
    GSTAT        = 0x01,
    IFCNT        = 0x02,
    SLAVECONF    = 0x03,
    IOIN         = 0x04,  // read; write variant is OUTPUT (same addr)
    X_COMPARE    = 0x05,
    OTP_PROG     = 0x06,
    OTP_READ     = 0x07,
    FACTORY_CONF = 0x08,
    SHORT_CONF   = 0x09,
    DRV_CONF     = 0x0A,
    GLOBAL_SCALER= 0x0B,
    OFFSET_READ  = 0x0C,

    // Velocity dependent driver features (0x10..0x1F)
    IHOLD_IRUN   = 0x10,
    TPOWERDOWN   = 0x11,
    TSTEP        = 0x12,
    TPWMTHRS     = 0x13,
    TCOOLTHRS    = 0x14,
    THIGH        = 0x15,

    // Ramp generator (0x20..0x2D)
    RAMPMODE     = 0x20,
    XACTUAL      = 0x21,
    VACTUAL      = 0x22,
    VSTART       = 0x23,
    A1           = 0x24,
    V1           = 0x25,
    AMAX         = 0x26,
    VMAX         = 0x27,
    DMAX         = 0x28,
    D1           = 0x2A,
    VSTOP        = 0x2B,
    TZEROWAIT    = 0x2C,
    XTARGET      = 0x2D,

    // Ramp-gen driver features (0x30..0x36)
    VDCMIN       = 0x33,
    SW_MODE      = 0x34,
    RAMP_STAT    = 0x35,
    XLATCH       = 0x36,

    // Encoder (0x38..0x3D)
    ENCMODE      = 0x38,
    X_ENC        = 0x39,
    ENC_CONST    = 0x3A,
    ENC_STATUS   = 0x3B,
    ENC_LATCH    = 0x3C,
    ENC_DEVIATION= 0x3D,

    // Microstep table & actuals (0x60..0x6B)
    MSLUT0       = 0x60,
    MSLUT1       = 0x61,
    MSLUT2       = 0x62,
    MSLUT3       = 0x63,
    MSLUT4       = 0x64,
    MSLUT5       = 0x65,
    MSLUT6       = 0x66,
    MSLUT7       = 0x67,
    MSLUTSEL     = 0x68,
    MSLUTSTART   = 0x69,
    MSCNT        = 0x6A,
    MSCURACT     = 0x6B,

    // Driver (0x6C..0x73)
    CHOPCONF     = 0x6C,
    COOLCONF     = 0x6D,
    DCCTRL       = 0x6E,
    DRV_STATUS   = 0x6F,
    PWMCONF      = 0x70,
    PWM_SCALE    = 0x71,
    PWM_AUTO     = 0x72,
    LOST_STEPS   = 0x73,
};

// ---------- Fields by register ----------

// 0x00 GCONF
namespace GCONF {
    static constexpr Field RECALIBRATE         = F<0,0>();
    static constexpr Field FASTSTANDSTILL      = F<1,1>();
    static constexpr Field EN_PWM_MODE         = F<2,2>();
    static constexpr Field MULTISTEP_FILT      = F<3,3>();
    static constexpr Field SHAFT               = F<4,4>();
    static constexpr Field DIAG0_ERROR         = F<5,5>();
    static constexpr Field DIAG0_OTPW          = F<6,6>();
    static constexpr Field DIAG0_STALL_or_STEP = F<7,7>();
    static constexpr Field DIAG1_STALL_or_DIR  = F<8,8>();
    static constexpr Field DIAG1_INDEX         = F<9,9>();
    static constexpr Field DIAG1_ONSTATE       = F<10,10>();
    static constexpr Field DIAG1_STEPS_SKIPPED = F<11,11>();
    static constexpr Field DIAG0_INT_PUSHPULL  = F<12,12>();
    static constexpr Field DIAG1_POSCOMP_PP    = F<13,13>();
    static constexpr Field SMALL_HYSTERESIS    = F<14,14>();
    static constexpr Field STOP_ENABLE         = F<15,15>();
    static constexpr Field DIRECT_MODE         = F<16,16>();
    static constexpr Field TEST_MODE           = F<17,17>();
}

// 0x01 GSTAT
namespace GSTAT {
    static constexpr Field RESET   = F<0,0>(); // w1c
    static constexpr Field DRV_ERR = F<1,1>(); // w1c
    static constexpr Field UV_CP   = F<2,2>(); // w1c
}

// 0x02 IFCNT (R)
namespace IFCNT { static constexpr Field COUNT = F<0,7>(); }

// 0x03 SLAVECONF (W)
namespace SLAVECONF {
    static constexpr Field SLAVEADDR = F<0,7>();
    static constexpr Field SENDDELAY = F<8,11>();
}

// 0x04 IOIN (R) and OUTPUT (W)
namespace IOIN {
    static constexpr Field REFL_STEP  = F<0,0>();
    static constexpr Field REFR_DIR   = F<1,1>();
    static constexpr Field ENCB_DCEN  = F<2,2>();
    static constexpr Field ENCA_DCIN  = F<3,3>();
    static constexpr Field DRV_ENN    = F<4,4>();
    static constexpr Field ENC_N_DCO  = F<5,5>();
    static constexpr Field SD_MODE    = F<6,6>();
    static constexpr Field SWCOMP_IN  = F<7,7>();
    static constexpr Field A2         = F<8,8>();
    static constexpr Field A1         = F<9,9>();
    static constexpr Field B2         = F<10,10>();
    static constexpr Field B1         = F<11,11>();
    static constexpr Field UART_EN    = F<12,12>();
    static constexpr Field STEP       = F<13,13>();
    static constexpr Field DIR        = F<14,14>();
    static constexpr Field DCEN_CFG4  = F<15,15>();
    static constexpr Field DCIN_CFG5  = F<16,16>();
    static constexpr Field DCO_CFG6   = F<17,17>();
    static constexpr Field VERSION    = F<24,31>(); // 0x30 typical
}
namespace OUTPUT { // write to 0x04
    static constexpr Field SDO_PUSHPULL = F<0,0>();
    static constexpr Field GPO1         = F<1,1>();
    static constexpr Field GPO2         = F<2,2>();
    static constexpr Field GPO3         = F<3,3>();
    static constexpr Field REFR_PU_PD   = F<8,9>();
    static constexpr Field REFL_PU_PD   = F<10,11>();
    static constexpr Field ENCA_PU_PD   = F<12,13>();
    static constexpr Field ENCB_PU_PD   = F<14,15>();
}

// 0x05 X_COMPARE (full 32)
namespace X_COMPARE { static constexpr Field VAL = F<0,31>(); }

// 0x06 OTP_PROG
namespace OTP_PROG {
    static constexpr Field OTPBIT    = F<0,2>();
    static constexpr Field OTPBYTE   = F<4,5>();
    static constexpr Field OTPMAGIC  = F<8,15>(); // 0xBD to enable
}

// 0x07 OTP_READ
namespace OTP_READ {
    static constexpr Field BYTE0 = F<0,7>();
    static constexpr Field BYTE1 = F<8,15>();
    static constexpr Field BYTE2 = F<16,23>();
    static constexpr Field BYTE3 = F<24,31>();
}

// 0x08 FACTORY_CONF
namespace FACTORY_CONF {
    static constexpr Field FCLKTRIM = F<0,4>();
    static constexpr Field OTTRIM   = F<8,10>();
}

// 0x09 SHORT_CONF
namespace SHORT_CONF {
    static constexpr Field S2VS_LEVEL   = F<0,3>();
    static constexpr Field SHORTFILTER  = F<4,5>();
    static constexpr Field S2G_LEVEL    = F<8,11>();
    static constexpr Field SHORTDELAY   = F<12,12>();
    static constexpr Field VSENSE       = F<15,15>();
}

// 0x0A DRV_CONF
namespace DRV_CONF {
    static constexpr Field BBMTIME     = F<0,4>();
    static constexpr Field BBMCLKS     = F<8,11>();
    static constexpr Field OTSELECT    = F<16,17>();
    static constexpr Field DRVSTRENGTH = F<18,19>();
    static constexpr Field FILT_ISENSE = F<20,21>();
}

// 0x0B GLOBAL_SCALER
namespace GLOBAL_SCALER { static constexpr Field SCALE = F<0,7>(); }

// 0x0C OFFSET_READ
namespace OFFSET_READ {
    static constexpr Field PHASE_B = F<0,7>();   // signed
    static constexpr Field PHASE_A = F<8,15>();  // signed
}

// 0x10 IHOLD_IRUN
namespace IHOLD_IRUN {
    static constexpr Field IHOLD      = F<0,4>();
    static constexpr Field IRUN       = F<8,12>();
    static constexpr Field IHOLDDELAY = F<16,19>();
}

// 0x11 TPOWERDOWN
namespace TPOWERDOWN { static constexpr Field TPD = F<0,7>(); }

// 0x12 TSTEP (R)
namespace TSTEP { static constexpr Field VAL = F<0,19>(); }

// 0x13 TPWMTHRS
namespace TPWMTHRS { static constexpr Field VAL = F<0,19>(); }


// 0x14 TCOOLTHRS
namespace TCOOLTHRS { static constexpr Field VAL = F<0,19>(); }

// 0x15 THIGH
namespace THIGH { static constexpr Field VAL = F<0,19>(); }

// 0x20 RAMPMODE
namespace RAMPMODE {
    enum Mode : uint32_t { POSITIONING=0, VEL_POS=1, VEL_NEG=2, HOLD=3 };
    static constexpr Field MODE = F<0,1>();
}

// 0x21..0x2D motion
namespace XACTUAL { static constexpr Field VAL = F<0,31>(); }  // signed
namespace VACTUAL { static constexpr Field VAL = F<0,23>(); }  // signed
namespace VSTART  { static constexpr Field VAL = F<0,17>(); }
namespace A1      { static constexpr Field VAL = F<0,15>(); }
namespace V1      { static constexpr Field VAL = F<0,19>(); }
namespace AMAX    { static constexpr Field VAL = F<0,15>(); }
namespace VMAX    { static constexpr Field VAL = F<0,22>(); }
namespace DMAX    { static constexpr Field VAL = F<0,15>(); }
namespace D1      { static constexpr Field VAL = F<0,15>(); }
namespace VSTOP   { static constexpr Field VAL = F<0,17>(); }
namespace TZEROWAIT { static constexpr Field VAL = F<0,15>(); }
namespace XTARGET { static constexpr Field VAL = F<0,31>(); }

// 0x33 VDCMIN
namespace VDCMIN { static constexpr Field VAL = F<8,22>(); }

// 0x34 SW_MODE
namespace SW_MODE {
    static constexpr Field STOP_L_ENABLE    = F<0,0>();
    static constexpr Field STOP_R_ENABLE    = F<1,1>();
    static constexpr Field POL_STOP_L       = F<2,2>();
    static constexpr Field POL_STOP_R       = F<3,3>();
    static constexpr Field SWAP_LR          = F<4,4>();
    static constexpr Field LATCH_L_ACTIVE   = F<5,5>();
    static constexpr Field LATCH_L_INACTIVE = F<6,6>();
    static constexpr Field LATCH_R_ACTIVE   = F<7,7>();
    static constexpr Field LATCH_R_INACTIVE = F<8,8>();
    static constexpr Field EN_LATCH_ENCODER = F<9,9>();
    static constexpr Field SG_STOP          = F<10,10>();
    static constexpr Field EN_SOFTSTOP      = F<11,11>();
}

// 0x35 RAMP_STAT
namespace RAMP_STAT {
    static constexpr Field STATUS_STOP_L     = F<0,0>();
    static constexpr Field STATUS_STOP_R     = F<1,1>();
    static constexpr Field STATUS_LATCH_L    = F<2,2>();  // w1c
    static constexpr Field STATUS_LATCH_R    = F<3,3>();  // w1c
    static constexpr Field EVENT_STOP_L      = F<4,4>();
    static constexpr Field EVENT_STOP_R      = F<5,5>();
    static constexpr Field EVENT_STOP_SG     = F<6,6>();  // w1c
    static constexpr Field EVENT_POS_REACHED = F<7,7>();  // w1c
    static constexpr Field VELOCITY_REACHED  = F<8,8>();
    static constexpr Field POSITION_REACHED  = F<9,9>();
    static constexpr Field VZERO             = F<10,10>();
    static constexpr Field T_ZEROWAIT_ACTIVE = F<11,11>();
    static constexpr Field SECOND_MOVE       = F<12,12>(); // w1c
    static constexpr Field STATUS_SG         = F<13,13>();
}

// 0x36 XLATCH
namespace XLATCH { static constexpr Field VAL = F<0,31>(); }

// 0x38 ENCMODE
namespace ENCMODE {
    static constexpr Field POL_A           = F<0,0>();
    static constexpr Field POL_B           = F<1,1>();
    static constexpr Field POL_N           = F<2,2>();
    static constexpr Field IGNORE_AB       = F<3,3>();
    static constexpr Field CLR_CONT        = F<4,4>();
    static constexpr Field CLR_ONCE        = F<5,5>();
    static constexpr Field POS_EDGE        = F<6,6>();
    static constexpr Field NEG_EDGE        = F<7,7>();
    static constexpr Field CLR_ENC_X       = F<8,8>();
    static constexpr Field LATCH_X_ACT     = F<9,9>();
    static constexpr Field ENC_SEL_DECIMAL = F<10,10>();
}

// 0x39 X_ENC
namespace X_ENC { static constexpr Field VAL = F<0,31>(); } // signed

// 0x3A ENC_CONST
namespace ENC_CONST { static constexpr Field VAL = F<0,15>(); }

// 0x3B ENC_STATUS
namespace ENC_STATUS {
    static constexpr Field N_EVENT        = F<0,0>(); // w1c
    static constexpr Field DEVIATION_WARN = F<1,1>(); // w1c
}

// 0x3C ENC_LATCH
namespace ENC_LATCH { static constexpr Field VAL = F<0,31>(); }

// 0x3D ENC_DEVIATION
namespace ENC_DEVIATION { static constexpr Field VAL = F<0,19>(); }

// 0x60..0x67 MSLUTx patterns (raw words)

// 0x68 MSLUTSEL
namespace MSLUTSEL {
    static constexpr Field X1 = F<0,6>();
    static constexpr Field X2 = F<8,14>();
    static constexpr Field X3 = F<16,22>();
    static constexpr Field W0 = F<24,25>();
    static constexpr Field W1 = F<26,27>();
    static constexpr Field W2 = F<28,29>();
    static constexpr Field W3 = F<30,31>();
}

// 0x69 MSLUTSTART
namespace MSLUTSTART {
    static constexpr Field START_SIN   = F<0,7>();
    static constexpr Field START_SIN90 = F<16,23>();
}

// 0x6A MSCNT
namespace MSCNT { static constexpr Field VAL = F<0,9>(); }

// 0x6B MSCURACT
namespace MSCURACT {
    static constexpr Field CUR_B = F<0,8>();   // signed
    static constexpr Field CUR_A = F<16,24>(); // signed
}

// 0x6C CHOPCONF
namespace CHOPCONF {
    static constexpr Field DISS2VS  = F<31,31>();
    static constexpr Field DISS2G   = F<30,30>();
    static constexpr Field DEDGE    = F<29,29>();
    static constexpr Field INTPOL   = F<28,28>();
    static constexpr Field MRES     = F<24,27>();
    static constexpr Field TPFD     = F<20,23>();
    static constexpr Field VHIGHCHM = F<19,19>();
    static constexpr Field VHIGHFS  = F<18,18>();
    static constexpr Field TBL      = F<15,16>();
    static constexpr Field CHM      = F<14,14>();
    static constexpr Field RNDTF    = F<13,13>(); // A-version
    static constexpr Field DISFDCC  = F<12,12>();
    static constexpr Field HEND     = F<7,10>();  // or OFFSET
    static constexpr Field HSTRT    = F<4,6>();   // or FD (low bits)
    static constexpr Field TOFF     = F<0,3>();
    // Combined FD helper when CHM=1
    static inline uint32_t set_fd_combined(uint32_t v, uint32_t fd) {
        v &= ~(((1u<<3)-1u) << 4);
        v &= ~(1u << 11);
        v |= ((fd & 0x7u) << 4);
        v |= ((fd & 0x8u) << (11-3));
        return v;
    }
    static inline uint32_t get_fd_combined(uint32_t v) {
        uint32_t low = (v >> 4) & 0x7u;
        uint32_t hi  = (v >> 11) & 0x1u;
        return (hi << 3) | low;
    }
}

// 0x6D COOLCONF
namespace COOLCONF {
    static constexpr Field SEMIN = F<0,3>();
    static constexpr Field SEUP  = F<5,6>();
    static constexpr Field SEMAX = F<8,11>();
    static constexpr Field SEDN  = F<13,14>();
    static constexpr Field SEIMIN= F<15,15>();
    static constexpr Field SGT   = F<16,22>(); // signed
    static constexpr Field SFILT = F<24,24>();
}

// 0x6E DCCTRL
namespace DCCTRL {
    static constexpr Field DC_TIME = F<0,9>();
    static constexpr Field DC_SG   = F<16,23>();
}

// 0x6F DRV_STATUS
namespace DRV_STATUS {
    static constexpr Field SG_RESULT = F<0,9>();
    static constexpr Field S2VSA     = F<12,12>();
    static constexpr Field S2VSB     = F<13,13>();
    static constexpr Field STEALTH   = F<14,14>();
    static constexpr Field FSACTIVE  = F<15,15>();
    static constexpr Field CS_ACTUAL = F<16,20>();
    static constexpr Field STALLGUARD= F<24,24>();
    static constexpr Field OT        = F<25,25>();
    static constexpr Field OTPW      = F<26,26>();
    static constexpr Field S2GA      = F<27,27>();
    static constexpr Field S2GB      = F<28,28>();
    static constexpr Field OLA       = F<29,29>();
    static constexpr Field OLB       = F<30,30>();
    static constexpr Field STST      = F<31,31>();
}

// 0x70 PWMCONF
namespace PWMCONF {
    static constexpr Field PWM_OFS       = F<0,7>();
    static constexpr Field PWM_GRAD      = F<8,15>();
    static constexpr Field PWM_FREQ      = F<16,17>();
    static constexpr Field PWM_AUTOSCALE = F<18,18>();
    static constexpr Field PWM_AUTOGRAD  = F<19,19>();
    static constexpr Field FREEWHEEL     = F<20,21>();
    static constexpr Field PWM_REG       = F<23,27>();
    static constexpr Field PWM_LIM       = F<27,31>();
}

// 0x71 PWM_SCALE
namespace PWM_SCALE {
    static constexpr Field PWM_SCALE_SUM  = F<0,7>();
    static constexpr Field PWM_SCALE_AUTO = F<16,24>(); // signed 9-bit
}

// 0x72 PWM_AUTO
namespace PWM_AUTO {
    static constexpr Field PWM_OFS_AUTO  = F<0,7>();
    static constexpr Field PWM_GRAD_AUTO = F<16,23>();
}

// 0x73 LOST_STEPS
namespace LOST_STEPS { static constexpr Field VAL = F<0,19>(); }

// ---------- Typed enums for discrete fields ----------
enum class TBL : uint32_t { TBL_16 = 0, TBL_24 = 1, TBL_36 = 2, TBL_54 = 3 };
enum class MicrostepRes : uint32_t {
    MS_256 = 0x0, MS_128 = 0x1, MS_64 = 0x2, MS_32 = 0x3,
    MS_16  = 0x4, MS_8   = 0x5, MS_4  = 0x6, MS_2  = 0x7, FULLSTEP = 0x8
};
inline uint32_t set_tbl(uint32_t chopconf, TBL v) {
    return CHOPCONF::TBL.set(chopconf, static_cast<uint32_t>(v));
}
inline uint32_t set_mres(uint32_t chopconf, MicrostepRes r) {
    return CHOPCONF::MRES.set(chopconf, static_cast<uint32_t>(r));
}

} // namespace tmc5160