name: CI

on:
  push:
    branches: [main, normal]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Update PlatformIO platforms/libs
        run: pio update

      # optional, speeds up repeated runs by caching ~/.platformio and .pio
      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
            .pio
          key: ${{ runner.os }}-pio-${{ hashFiles('platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-pio-

      - name: Run native unit tests
        run: pio test -e native

      - name: Build firmware (ELF)
        run: pio run -e nucleo_f303k8_mbed

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-elf
          path: .pio/build/nucleo_f303k8_mbed/firmware.elf

  release:
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Download firmware artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware-elf
          path: build-output

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: build-output/firmware.elf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
